### ISSUE TITLE
Test resiliance of contianer ant DB when makedown

### ISSUE THREAD

**Issue by maofalt** [maofalt/Transcendence#228]
Test all db  to see if there is resiliance in  the project. 
Right now the  migrations  break this resiliance.
E.g.:
Start the project. 
All the defautl accoutns are there
Make down. 
Restart rpoject. 
Migratiosn are gone.

We should test this before  pushing the project. Not critical but has to be done at the end.

**Comment by ionorb** [comment]
This was done in #341
