### ISSUE TITLE
New users aren't added to tournament db

### ISSUE THREAD

**Issue by ionorb** [maofalt/Transcendence#323]
When I create a new user and then try to get from the following endpoint: `/api/tournament/stats/yridgway/`, it returns with: `500 Internal Server Error`, and:
![Screenshot 2024-04-15 at 14 04 50](https://github.com/maofalt/Transcendence/assets/71927888/087945fd-7bb2-4f4b-a63b-677cce81478a)

This is a problem because then we can't create new users, but it is also a problem because it should at least return `401 Not Found` or `400 Bad Request`. It should also be returning json, not text in this way.

I suspect this is happening because when a new user is created they are not added to the tournaments db.

**Comment by maofalt** [comment]
from ym side whne creating anew user i got this error form the backend 
Forbidden (CSRF cookie not set.): /api/user_management/auth/validate_playername
[15/Apr/2024 12:15:11] "POST /api/user_management/auth/validate_playername HTTP/1.1" 403 2869
