### ISSUE TITLE
csrf token stopping first login

### ISSUE THREAD

**Issue by ionorb** [maofalt/Transcendence#372]
When trying to login for the first time it doesnt work due to missing csrf token.

**Comment by coisu** [comment]
This is only happen on first try Login on new incognito window, cause the browser settings in the incognito window are configured to disable cookies. and from most of user_management back-end code is protected aainst CSRF. so the necessary CSRF token supposed to be included in the requests. so it is normal. i think we don't need to handle this issue.

**Comment by ionorb** [comment]
Yes. But we can fix this problem. This also happens on non incognito if you close the browser and start it. I talked about it with @maofalt yesterday. We need an endpoint that is unprotected that sends the card token on first connection to the site.
